SELECT
    II.ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM
    ITEM_INFO II
    INNER JOIN ITEM_TREE IT
        ON II.ITEM_ID=IT.ITEM_ID
WHERE 1=1
    AND IT.ITEM_ID NOT IN(SELECT PARENT_ITEM_ID
                          FROM ITEM_TREE
                          WHERE PARENT_ITEM_ID IS NOT NULL
                          GROUP BY PARENT_ITEM_ID)
ORDER BY
    II.ITEM_ID DESC