-- 코드를 입력하세요
SELECT 
    EXTRACT(YEAR FROM s.SALES_DATE) AS YEAR, 
    EXTRACT(MONTH FROM s.SALES_DATE) AS MONTH, 
    i.GENDER, 
    COUNT(DISTINCT i.USER_ID) AS USERS
FROM 
    USER_INFO i 
JOIN 
    ONLINE_SALE s ON i.USER_ID = s.USER_ID
WHERE 
    i.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM s.SALES_DATE), 
    EXTRACT(MONTH FROM s.SALES_DATE), 
    i.GENDER
ORDER BY 
    YEAR, MONTH, GENDER;