SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS d
WHERE EXISTS ( # 값이 존재할 경우 TURE 반환
    SELECT 1 
    FROM SKILLCODES s
    WHERE s.NAME IN ('Python', 'C#')
    AND d.SKILL_CODE & s.CODE = s.CODE
)
ORDER BY ID;
