SELECT YEAR, 
       ABS(SIZE_OF_COLONY - MAX_SIZE_OF_COLONY) AS YEAR_DEV,
       ID
FROM (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
           MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS MaxSizes
JOIN ECOLI_DATA ON YEAR(DIFFERENTIATION_DATE) = MaxSizes.YEAR
ORDER BY YEAR, YEAR_DEV;